name: Hexo Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          rm -f ~/.ssh/id_rsa
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          echo "$ACTION_DEPLOY_KEY"
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "201357337@qq.com"
          git config --global user.name "loveyy520"
          rm -rf .deploy_git
          npm install hexo-cli hexo-deployer-git -g
          npm install

      - name: Deploy
        run: |
          hexo clean
          hexo g
